name: Release

"on":
  release:
    types:
      - published

jobs:
  release:
    name: Release artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Adjust version number
        shell: bash
        run: |
          yq -i -o json '.version="${{ github.event.release.tag_name }}"' \
            "${{ github.workspace }}/custom_components/nctalkbot/manifest.json"

      - name: Zip the integration directory
        shell: bash
        run: |
          cd "${{ github.workspace }}/custom_components/nctalkbot"
          zip nctalkbot.zip -r ./

      - name: Upload the zip file to the release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/custom_components/nctalkbot/nctalkbot.zip
